version: '3.1'

services:
  redis:
    image: redis:7.4-bookworm
    ports:
      - 6379:6379

  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: sh
    command: -c 'mkdir -p /data/bucket && minio server --console-address ":9001" /data'
    environment:
        MINIO_ACCESS_KEY: MINIO_ACCESS_KEY
        MINIO_SECRET_KEY: MINIO_SECRET_KEY
    deploy:
      restart_policy:
        condition: on-failure

  api:
    build:
      dockerfile: Dockerfile.api_server
      context: ./server
    ports:
      - 3005:3005
    depends_on:
      - redis
    volumes:
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  worker:
    build:
      dockerfile: Dockerfile.celery_worker
      context: ./server
    depends_on:
      - redis
      - minio
    volumes:
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  dashboard:
    build:
      dockerfile: Dockerfile.celery_worker
      context: ./server
    command: celery --broker=redis://redis:6379/0 --app=worker.celery flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
      - worker
