apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: dashboard
        image: ghcr.io/praneethtkonda/web-crawler-dashboard:0.5
        command: ["celery"]
        args: ["--broker=redis://redis:6379/0", "--app=worker.celery", "flower", "--port=5555"]
        ports:
        - containerPort: 5555
        env:
        - name: CELERY_BROKER_URL
          value: redis://redis:6379/0
        - name: CELERY_RESULT_BACKEND
          value: redis://redis:6379/0
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  selector:
    app: dashboard
  ports:
  - port: 5556
    targetPort: 5555