apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: worker
        image: ghcr.io/praneethtkonda/web-crawler-worker:0.5
        env: # TODO: Use kubernetes secrets
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_ACCESS_KEY
          value: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          value: MINIO_SECRET_KEY
